# Generated by Django 5.2.7 on 2025-11-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_producto_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='especificaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
