# Generated by Django 5.2.7 on 2025-11-14 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_carrito_carritoitem_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['id']},
        ),
    ]
