# Generated by Django 5.2.7 on 2025-11-14 15:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_carrito_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carrito',
            unique_together={('usuario',)},
        ),
    ]
